project:
  type: website
website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Proejct Summary
        href: project summary.qmd
      - text: Project Team
        href: project teams and staff.qmd
      - text: Activities
        href: activities.qmd
      - text: Deliverables
        href: deliverables.qmd
      - text: Contact
        href: contact.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
        href: https://github.com
format:
  html:
    theme: cosmo
    css: styles.css
