---
title: "Team"
---

# Meet the Team

Our project is led by a diverse team of experts from various fields:

+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Name and function            |     | Organisation       |     | Role/tasks/professional profile and expertise                                                             |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Ali Erken                    |     | Marmara University |     | Role: Person Responsible for the Financial and Administrative Issues, Lead Researcher and Lecturer        |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Project Manager              |     |                    |     | Professional Profile: Assoc. Prof., Political History                                                     |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Researcher                   |     |                    |     | Expertise: Soft Power, Turkey, Balkans Regions                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Lecturer                     |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Prof. Emirhan Güral          |     | Marmara University |     | Role: Senior advisor, researcher, and lecturer                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Senior Researcher            |     |                    |     | Professional Profile: Prof., International Relations                                                      |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     |                              |     |                    |     | Expertise: European Union, EU Integration, EU Enlargement                                                 |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Assoc. Prof. Hakan Mehmetcik |     | Marmara University |     | Role: Senior advisor, researcher, and lecturer                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Senior Researcher            |     |                    |     | Professional Profile: Assoc. Prof. in International Relations                                             |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     |                              |     |                    |     | Expertise: EU Integration, Regionalism                                                                    |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Prof. Vugar Imanbeyli        |     | Marmara University |     | Role: Senior advisor, researcher, and lecturer                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Senior Researcher            |     |                    |     | Professional Profile: Prof. in International Relations                                                    |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     |                              |     |                    |     | Expertise: Russian Politics, EU-Russian Relations, Russian-Turkish relations                              |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Assoc. Prof. Selin Bölme     |     | Marmara University |     | Role: Researcher, and lecturer                                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Senior Researcher            |     |                    |     | Professional Profile: Assoc. Prof, International Relations                                                |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     |                              |     |                    |     | Expertise: International Relations, Soft Power, US foreign policy                                         |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     | Prof. Nuri Tınaz             |     | Marmara University |     | Role: Researcher, and lecturer                                                                            |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     | Researcher                   |     |                    |     | Professional Profile: Prof. in Sociology                                                                  |     |
|     |                              |     |                    |     |                                                                                                           |     |
|     |                              |     |                    |     | Expertise: Minorities in the West, Muslims in Europe, Sociology of Integration, EU Projects and Education |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
|     |                              |     |                    |     |                                                                                                           |     |
+-----+------------------------------+-----+--------------------+-----+-----------------------------------------------------------------------------------------------------------+-----+
